spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.202:1521/kfdb.zt
    hikari:
      username: gsywjz
      password: zenithinfo
      minimum-idle: 10
      maximum-pool-size: 25
      idle-timeout: 300000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: select 1 from dual
  rabbitmq:
    username: admin
    password: admin
    host: 192.168.0.203
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      #若消息没有被路由到queue则进入ReturnCallback，否则丢弃消息
      mandatory: true
  redis:
    timeout: 6000ms
    database: 0
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    password: zenithinfo
    cluster:
      nodes:
        - 192.168.0.201:6379
        - 192.168.0.201:6380
        - 192.168.0.202:6379
        - 192.168.0.202:6380
        - 192.168.0.203:6379
        - 192.168.0.203:6380
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl